version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
        - autosubmit
    # Updating patch versions for "github-actions" is too chatty.
    # See https://github.com/flutter/flutter/issues/158350.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
