name: tool_metadata

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^3.3.1
  args: any
  collection:
  css_colors: ^1.1.1
  flutter:
    sdk: flutter
  path: ^1.8.1

dev_dependencies:
  grinder: ^0.9.0
  lints: ^1.0.1
