name: tool_metadata

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.40.0
  args: any
  css_colors: ^1.1.1
  flutter:
    sdk: flutter
  path: ^1.7.0

dev_dependencies:
  grinder: ^0.8.0
  lints: ^1.0.0
