name: tool_metadata

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^6.2.0
  args: ^2.4.2
  collection: ^1.18.0
  css_colors: ^1.1.1
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  grinder: ^0.9.4
  lints: ^2.1.1
  yaml: ^3.1.2
